### ISSUE TITLE
Mesh Central Router - RDP option not working

### ISSUE THREAD

**Issue by mcallisaya79** [Ylianst/MeshCentralRouter#60]
**Describe the bug**
MeshCentralRouter is unable to open the RDP option since last update (using the latest MCRouter version)
![image](https://github.com/Ylianst/MeshCentralRouter/assets/144259718/42864a32-0a4d-438e-962d-59a399a6c79e)

**To Reproduce**
1. Opening the app 
2. login and trying to run the RDP option from any computer

* Expected behavior**
It should Open the Remote desktop app (on Windows)
No response / no action

**Additional context**
Any Windows workstations is able to use the MeshCentrar RDP option
Tested running it as Administrator

I also run the debug and got next results:
ExceptionSink: System.NullReferenceException: Object reference not set to an instance of an object.
at MeshCentralRouter.MainForm.QuickMap(Int32 protocol, Int32 port, Int32 appId, NodeClass node)
at MeshCentralRouter.MainForm.rdpToolStripMenuItem_Click(Object sender, EventArgs e)
at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ToolStrip.WndProc(Message& m)
at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by mcallisaya79** [comment]
seems that our server was updated last night to the latest version and it´s generating the issue (1.1.13).

**Comment by mcallisaya79** [comment]
I was able to run with the newest version.  The problem now is that RDP option is not working:

ExceptionSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshCentralRouter.MainForm.QuickMap(Int32 protocol, Int32 port, Int32 appId, NodeClass node)
   at MeshCentralRouter.MainForm.rdpToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by risturiz** [comment]
Can confirm this with last version 1.1.15

**Comment by mcallisaya79** [comment]
> Can confirm this with last version 1.1.15
Yes, this keeps happening on the latest version, also downloaded the latest MCRDP version (1.8.8680)
ExceptionSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshCentralRouter.MainForm.QuickMap(Int32 protocol, Int32 port, Int32 appId, NodeClass node)
   at MeshCentralRouter.MainForm.rdpToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by si458** [comment]
please try the latest version which includes fixes from the master branch which has been merged
[MeshCentralRouter.zip](https://github.com/user-attachments/files/16016203/MeshCentralRouter.zip)
